
import { Appointment, DashboardSummary, Doctor, Patient, User } from './types';

// Current user (for simulation)
export const currentUser: User = {
  id: 'admin1',
  name: 'Admin User',
  email: 'admin@medappt.com',
  role: 'admin',
  avatar: 'https://ui-avatars.com/api/?name=Admin+User&background=0077B6&color=fff',
};

// Mock Doctors
export const doctors: Doctor[] = [
  {
    id: 'doc1',
    name: 'Dr. Maria Silva',
    email: 'maria.silva@medappt.com',
    specialty: 'Cardiologist',
    avatar: 'https://ui-avatars.com/api/?name=Maria+Silva&background=0077B6&color=fff',
    phone: '+55 11 99999-1111',
    bio: 'Cardiologist with 15 years of experience. Specializes in heart disease prevention and treatment.',
  },
  {
    id: 'doc2',
    name: 'Dr. Carlos Mendes',
    email: 'carlos.mendes@medappt.com',
    specialty: 'Dermatologist',
    avatar: 'https://ui-avatars.com/api/?name=Carlos+Mendes&background=0077B6&color=fff',
    phone: '+55 11 99999-2222',
    bio: 'Dermatologist focused on skin health and treatment of dermatological conditions.',
  },
  {
    id: 'doc3',
    name: 'Dr. Ana Costa',
    email: 'ana.costa@medappt.com',
    specialty: 'Pediatrician',
    avatar: 'https://ui-avatars.com/api/?name=Ana+Costa&background=0077B6&color=fff',
    phone: '+55 11 99999-3333',
    bio: 'Pediatrician with expertise in child development and preventive care.',
  },
  {
    id: 'doc4',
    name: 'Dr. João Pereira',
    email: 'joao.pereira@medappt.com',
    specialty: 'Orthopedist',
    avatar: 'https://ui-avatars.com/api/?name=João+Pereira&background=0077B6&color=fff',
    phone: '+55 11 99999-4444',
    bio: 'Orthopedist specializing in sports injuries and joint conditions.',
  },
];

// Mock Patients
export const patients: Patient[] = [
  {
    id: 'pat1',
    name: 'Roberto Almeida',
    email: 'roberto.almeida@email.com',
    phone: '+55 11 99999-5555',
    dateOfBirth: '1985-06-15',
    healthInsurance: 'MedPlus',
    avatar: 'https://ui-avatars.com/api/?name=Roberto+Almeida&background=00B4D8&color=fff',
  },
  {
    id: 'pat2',
    name: 'Juliana Santos',
    email: 'juliana.santos@email.com',
    phone: '+55 11 99999-6666',
    dateOfBirth: '1990-03-22',
    healthInsurance: 'HealthCare',
    avatar: 'https://ui-avatars.com/api/?name=Juliana+Santos&background=00B4D8&color=fff',
  },
  {
    id: 'pat3',
    name: 'Marcos Oliveira',
    email: 'marcos.oliveira@email.com',
    phone: '+55 11 99999-7777',
    dateOfBirth: '1978-11-10',
    healthInsurance: 'MedPlus',
    avatar: 'https://ui-avatars.com/api/?name=Marcos+Oliveira&background=00B4D8&color=fff',
  },
  {
    id: 'pat4',
    name: 'Lucia Ferreira',
    email: 'lucia.ferreira@email.com',
    phone: '+55 11 99999-8888',
    dateOfBirth: '1995-08-30',
    healthInsurance: 'NationalHealth',
    avatar: 'https://ui-avatars.com/api/?name=Lucia+Ferreira&background=00B4D8&color=fff',
  },
  {
    id: 'pat5',
    name: 'Fernando Costa',
    email: 'fernando.costa@email.com',
    phone: '+55 11 99999-9999',
    dateOfBirth: '1982-04-18',
    healthInsurance: 'HealthCare',
    avatar: 'https://ui-avatars.com/api/?name=Fernando+Costa&background=00B4D8&color=fff',
  },
];

// Mock Appointments
export const appointments: Appointment[] = [
  {
    id: 'app1',
    patientId: 'pat1',
    patientName: 'Roberto Almeida',
    doctorId: 'doc1',
    doctorName: 'Dr. Maria Silva',
    doctorSpecialty: 'Cardiologist',
    date: '2025-04-05',
    time: '09:00',
    status: 'scheduled',
  },
  {
    id: 'app2',
    patientId: 'pat2',
    patientName: 'Juliana Santos',
    doctorId: 'doc3',
    doctorName: 'Dr. Ana Costa',
    doctorSpecialty: 'Pediatrician',
    date: '2025-04-05',
    time: '10:30',
    status: 'confirmed',
  },
  {
    id: 'app3',
    patientId: 'pat3',
    patientName: 'Marcos Oliveira',
    doctorId: 'doc4',
    doctorName: 'Dr. João Pereira',
    doctorSpecialty: 'Orthopedist',
    date: '2025-04-05',
    time: '14:00',
    status: 'scheduled',
  },
  {
    id: 'app4',
    patientId: 'pat4',
    patientName: 'Lucia Ferreira',
    doctorId: 'doc2',
    doctorName: 'Dr. Carlos Mendes',
    doctorSpecialty: 'Dermatologist',
    date: '2025-04-06',
    time: '11:00',
    status: 'scheduled',
  },
  {
    id: 'app5',
    patientId: 'pat5',
    patientName: 'Fernando Costa',
    doctorId: 'doc1',
    doctorName: 'Dr. Maria Silva',
    doctorSpecialty: 'Cardiologist',
    date: '2025-04-06',
    time: '15:30',
    status: 'scheduled',
  },
  {
    id: 'app6',
    patientId: 'pat2',
    patientName: 'Juliana Santos',
    doctorId: 'doc2',
    doctorName: 'Dr. Carlos Mendes',
    doctorSpecialty: 'Dermatologist',
    date: '2025-04-04',
    time: '09:30',
    status: 'completed',
    notes: 'Patient reported skin irritation. Prescribed antihistamine cream.',
  },
  {
    id: 'app7',
    patientId: 'pat3',
    patientName: 'Marcos Oliveira',
    doctorId: 'doc1',
    doctorName: 'Dr. Maria Silva',
    doctorSpecialty: 'Cardiologist',
    date: '2025-04-04',
    time: '11:00',
    status: 'completed',
    notes: 'Routine check-up. Blood pressure normal.',
  },
  {
    id: 'app8',
    patientId: 'pat1',
    patientName: 'Roberto Almeida',
    doctorId: 'doc4',
    doctorName: 'Dr. João Pereira',
    doctorSpecialty: 'Orthopedist',
    date: '2025-04-03',
    time: '16:00',
    status: 'cancelled',
  },
];

// Dashboard Summary Data
export const dashboardSummary: DashboardSummary = {
  totalAppointments: appointments.length,
  todayAppointments: appointments.filter(app => app.date === '2025-04-05').length,
  upcomingAppointments: appointments.filter(app => ['scheduled', 'confirmed'].includes(app.status)).length,
  completedAppointments: appointments.filter(app => app.status === 'completed').length,
  cancelledAppointments: appointments.filter(app => app.status === 'cancelled').length,
  totalDoctors: doctors.length,
  totalPatients: patients.length,
};
