// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxzynszdksdhrkyjlbss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4enluc3pka3NkaHJreWpsYnNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODExOTQsImV4cCI6MjA1OTk1NzE5NH0.qyu9_pXqNGFryi979tAoC4kd6AHWdE5UNMeN-wMk1Hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);